import { z } from "zod"
import type { AppSettings, Task } from "../types"

export type GeneratedTask = Pick<Task, "name" | "description" | "priority" | "difficulty" | "estimatedMinutes" | "energy" | "suggestedStartTime" | "preferredDaypart" | "timingConstraintSource" | "timingReason" | "subtasks" | "warnings"> & { selected: boolean; clientId: string; scheduledFor?: string; sourceExcerpt?: string }
const uid = () => crypto.randomUUID()
const taskSchema = z.object({ name: z.string().min(1).max(120), description: z.string().max(500), priority: z.enum(["urgent", "scheduled", "optional"]), difficulty: z.enum(["light", "standard", "challenging"]), estimatedMinutes: z.number().int().min(5).max(480), energy: z.enum(["low", "medium", "high"]), suggestedStartTime: z.string().regex(/^\d{2}:\d{2}$/).optional(), preferredDaypart: z.enum(["morning", "afternoon", "evening", "night", "anytime"]), timingConstraintSource: z.enum(["explicit", "inferred", "none"]), timingReason: z.string(), subtasks: z.array(z.object({ id: z.string(), title: z.string(), completed: z.boolean(), estimatedMinutes: z.number().optional() })).max(5), warnings: z.array(z.string()).max(8), selected: z.boolean(), clientId: z.string(), scheduledFor: z.string().optional() })

function priority(text: string): GeneratedTask["priority"] { return /urgent|asap|deadline|must|submit|today/i.test(text) ? "urgent" : /class|meeting|call|appointment|tomorrow/i.test(text) ? "scheduled" : "optional" }
function difficulty(text: string): GeneratedTask["difficulty"] { return /assignment|project|build|implement|study|revise|research|portfolio/i.test(text) ? "challenging" : /write|review|practice|plan|finish/i.test(text) ? "standard" : "light" }
function duration(text: string, level: GeneratedTask["difficulty"]): number { const match = text.match(/\b(\d{1,3})\s*(minutes?|mins?|hours?|hrs?)\b/i); if (match) return Math.max(5, Math.min(480, Number(match[1]) * (/hour|hr/i.test(match[2]) ? 60 : 1))); return /assignment|project|build|research/i.test(text) ? 75 : /study|revise|practice/i.test(text) ? 45 : level === "standard" ? 30 : 15 }
function timing(text: string): Pick<GeneratedTask, "suggestedStartTime" | "preferredDaypart" | "timingConstraintSource" | "timingReason"> { const exact = text.match(/\b([01]?\d|2[0-3]):([0-5]\d)\b/) || text.match(/\b(1[0-2]|0?[1-9])(?::([0-5]\d))?\s*(am|pm)\b/i); if (exact) { let hour = Number(exact[1]); if (exact[3]) { hour %= 12; if (exact[3].toLowerCase() === "pm") hour += 12 }; const time = `${String(hour).padStart(2, "0")}:${exact[2] || "00"}`; return { suggestedStartTime: time, preferredDaypart: "anytime", timingConstraintSource: "explicit", timingReason: "You gave an exact time." } }; const daypart = (["morning", "afternoon", "evening", "night"] as const).find(v => text.toLowerCase().includes(v)); if (daypart) return { suggestedStartTime: { morning: "09:00", afternoon: "14:00", evening: "19:00", night: "21:00" }[daypart], preferredDaypart: daypart, timingConstraintSource: "inferred", timingReason: `You said ${daypart}; this time is an editable suggestion.` }; return { preferredDaypart: "anytime", timingConstraintSource: "none", timingReason: "No exact time was given; this remains flexible." } }

export function createLocalPlan(transcript: string, scheduledFor = new Date().toISOString().slice(0, 10), settings?: AppSettings): { tasks: GeneratedTask[]; warnings: string[] } {
  const parts = transcript.split(/\n|;|(?<=\.)\s+|,(?=\s*(?:then )?[A-Za-z])/).map(v => v.trim()).filter(Boolean).slice(0, 12)
  const tasks = parts.map(part => { const level = difficulty(part), minutes = duration(part, level), optional = /maybe|if possible|if i have energy/i.test(part), subtasks = minutes > 30 && /assignment|project|build|study|revise|research/i.test(part) ? ["Define the next concrete outcome", "Do the focused work", "Check and record follow-up"].map((title, index) => ({ id: uid(), title, completed: false, estimatedMinutes: Math.max(5, Math.round(minutes / 3)), order: index })) : []; return taskSchema.parse({ clientId: uid(), selected: true, name: part.charAt(0).toUpperCase() + part.slice(1), description: `Complete this clearly defined outcome: ${part}`, priority: optional ? "optional" : priority(part), difficulty: level, estimatedMinutes: minutes, energy: level === "challenging" ? "high" : level === "light" ? "low" : "medium", scheduledFor, ...timing(part), subtasks, warnings: [] }) })
  const total = tasks.reduce((sum, task) => sum + task.estimatedMinutes, 0), limit = settings?.preferences.maxPlannedMinutesPerDay || 360
  return { tasks, warnings: total > limit ? [`This plan contains about ${total} minutes, above your ${limit}-minute daily limit. Review optional tasks before saving.`] : [] }
}
