"use client"
import { useEffect, useMemo, useState } from "react"
import { CalendarDays, Check, Circle, Download, Home, Loader2, Plus, Settings, Sparkles, Trash2, Trophy } from "lucide-react"
import { parseISO } from "date-fns"
import ModelManager from "./components/model-manager"
import type { AppSettings, GeneratedTask, Jar, Priority, Difficulty, Task } from "./types"
import { generateOnDevice, getInstalledModelIds, hasWebGpu } from "./lib/local-ai"
import { DAYS, buildDailyPrompt, buildWeeklyPrompt, extractJsonArray, fallbackDailyPlan, fallbackWeeklyPlan, getMonday, getWeekDateMap, normalizeGeneratedDaily, normalizeGeneratedWeekly, toDateKey } from "./lib/planner"
import { buildJourneyMarkdown, downloadJourneyMarkdown } from "./lib/export-markdown"

type View = "today"|"week"|"journey"|"settings"
const K={entered:"taskjar_entered",tasks:"taskjar_tasks",jars:"taskjar_jars",settings:"taskjar_settings"}
const base:AppSettings={studentName:"Student",xpValues:{light:5,standard:10,challenging:15},jarTarget:100,emojis:{priority:{urgent:"🔴",scheduled:"🟡",optional:"🟢"},difficulty:{light:"🍃",standard:"⚡",challenging:"🔥"}},preferences:{soundEnabled:false,theme:"dark"},localAI:{selectedModelId:"gemma-270m"}}
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`
const freshJar=(target:number):Jar=>({id:uid(),currentXP:0,targetXP:target,completed:false,tasks:[]})
const merge=(v?:Partial<AppSettings>):AppSettings=>({...base,...v,xpValues:{...base.xpValues,...v?.xpValues},emojis:{priority:{...base.emojis.priority,...v?.emojis?.priority},difficulty:{...base.emojis.difficulty,...v?.emojis?.difficulty}},preferences:{...base.preferences,...v?.preferences,theme:"dark"},localAI:{...base.localAI,...v?.localAI}})
function task(v:Partial<Task>):Task{const priority=(["urgent","scheduled","optional"].includes(String(v.priority))?v.priority:"optional") as Priority;const difficulty=(["light","standard","challenging"].includes(String(v.difficulty))?v.difficulty:"standard") as Difficulty;let day=v.scheduledFor;if(day&&!/^\d{4}-\d{2}-\d{2}$/.test(day)){const d=new Date(day);day=Number.isNaN(d.getTime())?undefined:toDateKey(d)}return{id:v.id||uid(),name:v.name||"Untitled task",description:v.description||"",priority,difficulty,priorityEmoji:v.priorityEmoji||base.emojis.priority[priority],difficultyEmoji:v.difficultyEmoji||base.emojis.difficulty[difficulty],xpValue:Number(v.xpValue)||base.xpValues[difficulty],completed:Boolean(v.completed),completedAt:v.completedAt,createdAt:Number(v.createdAt)||Date.now(),scheduledFor:day,source:v.source||"manual",originalPrompt:v.originalPrompt}}

export default function App(){
 const [ready,setReady]=useState(false),[entered,setEntered]=useState(false),[view,setView]=useState<View>("today"),[tasks,setTasks]=useState<Task[]>([]),[jars,setJars]=useState<Jar[]>([]),[settings,setSettings]=useState(base),[input,setInput]=useState(""),[weekInput,setWeekInput]=useState(""),[weekStart,setWeekStart]=useState(toDateKey(getMonday())),[drafts,setDrafts]=useState<GeneratedTask[]>([]),[mode,setMode]=useState<"daily"|"weekly">("daily"),[busy,setBusy]=useState(false),[notice,setNotice]=useState("")
 const today=toDateKey(new Date()),currentJar=jars.find(j=>!j.completed)||jars.at(-1),weekMap=useMemo(()=>getWeekDateMap(weekStart),[weekStart])
 useEffect(()=>{try{setEntered(localStorage.getItem(K.entered)==="1");const s=merge(JSON.parse(localStorage.getItem(K.settings)||"null")||undefined);setSettings(s);setTasks(JSON.parse(localStorage.getItem(K.tasks)||"[]").map(task));const j=JSON.parse(localStorage.getItem(K.jars)||"[]");setJars(j.length?j:[freshJar(s.jarTarget)])}catch{setJars([freshJar(100)])}finally{setReady(true)}},[])
 useEffect(()=>{if(ready)localStorage.setItem(K.tasks,JSON.stringify(tasks))},[tasks,ready]);useEffect(()=>{if(ready)localStorage.setItem(K.jars,JSON.stringify(jars))},[jars,ready]);useEffect(()=>{if(ready)localStorage.setItem(K.settings,JSON.stringify(settings))},[settings,ready])
 const todayTasks=tasks.filter(t=>t.scheduledFor?t.scheduledFor<=today:toDateKey(new Date(t.createdAt))===today).sort((a,b)=>Number(a.completed)-Number(b.completed))
 async function plan(kind:"daily"|"weekly"){const text=kind==="daily"?input:weekInput;if(!text.trim())return;setBusy(true);try{const installed=(await getInstalledModelIds()).includes(settings.localAI.selectedModelId);if(installed&&hasWebGpu()){const prompt=kind==="daily"?buildDailyPrompt(text,today):buildWeeklyPrompt(text,weekStart);const out=extractJsonArray((await generateOnDevice(settings.localAI.selectedModelId,prompt)).text);setDrafts(kind==="daily"?normalizeGeneratedDaily(out):normalizeGeneratedWeekly(out,weekStart));setNotice("Generated privately on this device.")}else{setDrafts(kind==="daily"?fallbackDailyPlan(text):fallbackWeeklyPlan(text,weekStart));setNotice("Used the offline rules planner; install a local model for richer results.")}setMode(kind)}catch(e){setDrafts(kind==="daily"?fallbackDailyPlan(text):fallbackWeeklyPlan(text,weekStart));setNotice(`${e instanceof Error?e.message:"Local AI failed"} Rules fallback used.`)}finally{setBusy(false)}}
 function addDrafts(){const source=mode==="daily"?"daily-ai":"weekly-ai",prompt=mode==="daily"?input:weekInput;setTasks(old=>[...drafts.map(d=>task({...d,id:uid(),createdAt:Date.now(),scheduledFor:d.scheduledFor||today,source,originalPrompt:prompt,priorityEmoji:settings.emojis.priority[d.priority],difficultyEmoji:settings.emojis.difficulty[d.difficulty],xpValue:settings.xpValues[d.difficulty]})),...old]);setDrafts([])}
 function toggle(t:Task){const done=!t.completed;setTasks(old=>old.map(x=>x.id===t.id?{...x,completed:done,completedAt:done?Date.now():undefined}:x));if(!done||!currentJar)return;const xp=currentJar.currentXP+t.xpValue;if(xp>=currentJar.targetXP){const filled={...currentJar,currentXP:currentJar.targetXP,completed:true,completedAt:Date.now(),tasks:[...currentJar.tasks,t.id]};setJars(old=>[...old.map(j=>j.id===currentJar.id?filled:j),{...freshJar(settings.jarTarget),currentXP:xp-currentJar.targetXP}])}else setJars(old=>old.map(j=>j.id===currentJar.id?{...j,currentXP:xp,tasks:[...j.tasks,t.id]}:j))}
 if(!ready)return <main className="loading"><Loader2 className="spin"/></main>
 if(!entered)return <main className="landing"><div><Sparkles size={42}/><p className="eyebrow">TASKJAR LOCAL</p><h1>Plan your work without an account.</h1><p>Tasks, progress and optional AI models stay in your browser. Export the whole journey as Markdown whenever you need another AI agent.</p><button onClick={()=>{localStorage.setItem(K.entered,"1");setEntered(true)}}>Open local workspace <Home size={17}/></button></div></main>
 const nav:[[View,React.ReactNode,string],[View,React.ReactNode,string],[View,React.ReactNode,string],[View,React.ReactNode,string]]=[["today",<Home/>,"Today"],["week",<CalendarDays/>,"Week"],["journey",<Trophy/>,"Journey"],["settings",<Settings/>,"Settings"]]
 return <main className="app"><aside><h2>TaskJar</h2><small>Local-first workspace</small>{nav.map(([v,i,l])=><button className={view===v?"active":""} key={v} onClick={()=>setView(v)}>{i}{l}</button>)}<div className="jar"><small>Current jar</small><progress value={currentJar?.currentXP||0} max={currentJar?.targetXP||100}/><span>{currentJar?.currentXP||0}/{currentJar?.targetXP||100} XP</span></div></aside><section className="content"><header><div><p className="eyebrow">STORED LOCALLY</p><h1>{view==="week"?"Weekly dump":view}</h1></div></header>{notice&&<p className="notice">{notice}</p>}
 {view==="today"&&<><section className="card"><h2>Turn today’s brain dump into tasks</h2><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Finish assignment, revise React hooks, email the organiser..."/><button disabled={busy} onClick={()=>plan("daily")}>{busy?<Loader2 className="spin"/>:<Sparkles/>} Make tasks</button></section><h2>Due today and carry-over</h2><div className="list">{todayTasks.length?todayTasks.map(t=><TaskRow key={t.id} t={t} toggle={()=>toggle(t)} remove={()=>setTasks(x=>x.filter(y=>y.id!==t.id))}/>):<p className="empty">Nothing planned yet.</p>}</div></>}
 {view==="week"&&<><section className="card"><h2>Organise a full week</h2><input type="date" value={weekStart} onChange={e=>setWeekStart(toDateKey(getMonday(parseISO(e.target.value))))}/><textarea value={weekInput} onChange={e=>setWeekInput(e.target.value)} placeholder="Monday finish landing page; Friday submit report..."/><button disabled={busy} onClick={()=>plan("weekly")}><CalendarDays/> Organise week</button></section><div className="week">{DAYS.map(d=><section className="card" key={d}><h3>{d}</h3><small>{weekMap[d]}</small>{tasks.filter(t=>t.scheduledFor===weekMap[d]).map(t=><p key={t.id}>{t.completed?"✓ ":"• "}{t.name}</p>)}</section>)}</div></>}
 {view==="journey"&&<><div className="stats"><section className="card"><b>{tasks.length}</b><small>Tasks</small></section><section className="card"><b>{tasks.filter(t=>t.completed).length}</b><small>Completed</small></section><section className="card"><b>{jars.filter(j=>j.completed).length}</b><small>Jars filled</small></section></div><section className="card"><h2>AI-ready Markdown</h2><p className="muted">Includes every task, status, date, source, milestone and a handoff prompt.</p><button onClick={()=>downloadJourneyMarkdown(tasks,jars,settings)}><Download/> Export journey</button><details><summary>Preview</summary><pre>{buildJourneyMarkdown(tasks,jars,settings)}</pre></details></section></>}
 {view==="settings"&&<><ModelManager selected={settings.localAI.selectedModelId} onSelect={id=>setSettings(s=>({...s,localAI:{selectedModelId:id}}))} onNotice={setNotice}/><section className="card"><h2>Local data</h2><label>Name<input value={settings.studentName} onChange={e=>setSettings(s=>({...s,studentName:e.target.value}))}/></label><button className="danger" onClick={()=>{if(confirm("Delete all local task history?")){setTasks([]);setJars([freshJar(settings.jarTarget)])}}}><Trash2/> Clear history</button></section></>}
 </section><nav className="mobile">{nav.map(([v,i,l])=><button className={view===v?"active":""} key={v} onClick={()=>setView(v)}>{i}<small>{l}</small></button>)}</nav>
 {drafts.length>0&&<div className="modal"><div><h2>Review generated tasks</h2>{drafts.map((d,i)=><article key={i}><b>{d.name}</b><p>{d.description}</p><small>{d.priority} · {d.difficulty} · {d.scheduledFor||today}</small></article>)}<div className="actions"><button className="quiet" onClick={()=>setDrafts([])}>Cancel</button><button onClick={addDrafts}><Plus/> Add all</button></div></div></div>}
 </main>}
function TaskRow({t,toggle,remove}:{t:Task;toggle:()=>void;remove:()=>void}){return <article className="task"><button className="icon" onClick={toggle}>{t.completed?<Check/>:<Circle/>}</button><div><b className={t.completed?"done":""}>{t.name}</b><p>{t.description}</p><small>{t.priorityEmoji} {t.priority} · {t.difficultyEmoji} {t.difficulty} · {t.scheduledFor||"today"}</small></div><button className="icon danger" onClick={remove}><Trash2/></button></article>}
